/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:37:22 GMT 2022
 */

package io.diffblue.corebanking;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.diffblue.corebanking.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.generateXdigitNumber((-2536));
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long long0 = Util.generateXdigitNumber(1);
      assertEquals(0L, long0);
      
      long long1 = Util.generateXdigitNumber(1);
      assertEquals(1L, long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Util util0 = new Util();
  }
}
