/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:21:44 GMT 2022
 */

package io.diffblue.corebanking.ui.menu;

import org.junit.Test;
import static org.junit.Assert.*;
import io.diffblue.corebanking.CoreBanking;
import io.diffblue.corebanking.client.Client;
import io.diffblue.corebanking.ui.menu.AccountsMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AccountsMenu_ESTest extends AccountsMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      AccountsMenu accountsMenu0 = new AccountsMenu(coreBanking0);
      Client client0 = new Client("IXJy).Gm@'|iqZ;yp");
      coreBanking0.openNewAccount(client0, 0L);
      accountsMenu0.executeMenuOption(1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      AccountsMenu accountsMenu0 = new AccountsMenu(coreBanking0);
      accountsMenu0.executeMenuOption(602);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      AccountsMenu accountsMenu0 = new AccountsMenu(coreBanking0);
      accountsMenu0.executeMenuOption(0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      AccountsMenu accountsMenu0 = new AccountsMenu(coreBanking0);
      accountsMenu0.executeMenuOption(2);
  }
}
