/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:21:23 GMT 2022
 */

package io.diffblue.corebanking.ui.menu;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.diffblue.corebanking.CoreBanking;
import io.diffblue.corebanking.account.Account;
import io.diffblue.corebanking.client.Client;
import io.diffblue.corebanking.ui.menu.ClientsMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClientsMenu_ESTest extends ClientsMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      Client client0 = new Client("");
      client0.addAccount((Account) null);
      coreBanking0.registerNewClient(client0);
      ClientsMenu clientsMenu0 = new ClientsMenu(coreBanking0);
      // Undeclared exception!
      try { 
        clientsMenu0.executeMenuOption(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("io.diffblue.corebanking.client.Client", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      ClientsMenu clientsMenu0 = new ClientsMenu(coreBanking0);
      Client client0 = new Client("EJ ;/(h[Cry;{BA");
      coreBanking0.registerNewClient(client0);
      clientsMenu0.executeMenuOption(1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      ClientsMenu clientsMenu0 = new ClientsMenu(coreBanking0);
      clientsMenu0.executeMenuOption((-1));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      ClientsMenu clientsMenu0 = new ClientsMenu(coreBanking0);
      clientsMenu0.executeMenuOption(0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      ClientsMenu clientsMenu0 = new ClientsMenu(coreBanking0);
      clientsMenu0.executeMenuOption(2);
      clientsMenu0.executeMenuOption(2);
  }
}
