/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:30:12 GMT 2022
 */

package io.diffblue.corebanking.ui.menu;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.diffblue.corebanking.CoreBanking;
import io.diffblue.corebanking.ui.menu.CoreBankingDataManagementMenu;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CoreBankingDataManagementMenu_ESTest extends CoreBankingDataManagementMenu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CoreBankingDataManagementMenu coreBankingDataManagementMenu0 = new CoreBankingDataManagementMenu((CoreBanking) null);
      // Undeclared exception!
      try { 
        coreBankingDataManagementMenu0.executeMenuOption(2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("io.diffblue.corebanking.datamanagement.ReadFromDB", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      CoreBankingDataManagementMenu coreBankingDataManagementMenu0 = new CoreBankingDataManagementMenu(coreBanking0);
      // Undeclared exception!
      coreBankingDataManagementMenu0.executeMenuOption(2);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      CoreBankingDataManagementMenu coreBankingDataManagementMenu0 = new CoreBankingDataManagementMenu(coreBanking0);
      coreBankingDataManagementMenu0.executeMenuOption(1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      CoreBankingDataManagementMenu coreBankingDataManagementMenu0 = new CoreBankingDataManagementMenu(coreBanking0);
      coreBankingDataManagementMenu0.executeMenuOption((-1392));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      CoreBankingDataManagementMenu coreBankingDataManagementMenu0 = new CoreBankingDataManagementMenu(coreBanking0);
      coreBankingDataManagementMenu0.executeMenuOption(0);
  }
}
