/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:37:34 GMT 2022
 */

package io.diffblue.corebanking.compliance.rules;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.diffblue.corebanking.account.Account;
import io.diffblue.corebanking.client.Client;
import io.diffblue.corebanking.compliance.rules.ComplianceRuleBalanceAboveOrEqualToZero;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComplianceRuleBalanceAboveOrEqualToZero_ESTest extends ComplianceRuleBalanceAboveOrEqualToZero_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ComplianceRuleBalanceAboveOrEqualToZero complianceRuleBalanceAboveOrEqualToZero0 = new ComplianceRuleBalanceAboveOrEqualToZero();
      Client client0 = new Client("io.diffblue.corebanking.compliance.rules.ComplianceRuleBalanceAboveOrEqualToZero");
      Account account0 = new Account(0L, client0, 4);
      complianceRuleBalanceAboveOrEqualToZero0.validateAccountCompliance(account0);
      assertEquals(Account.AccountState.OPEN, account0.getAccountState());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ComplianceRuleBalanceAboveOrEqualToZero complianceRuleBalanceAboveOrEqualToZero0 = new ComplianceRuleBalanceAboveOrEqualToZero();
      // Undeclared exception!
      try { 
        complianceRuleBalanceAboveOrEqualToZero0.validateAccountCompliance((Account) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("io.diffblue.corebanking.compliance.rules.ComplianceRuleBalanceAboveOrEqualToZero", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ComplianceRuleBalanceAboveOrEqualToZero complianceRuleBalanceAboveOrEqualToZero0 = new ComplianceRuleBalanceAboveOrEqualToZero();
      Client client0 = new Client("io.diffblue.corebanking.compliance.rules.ComplianceRuleBalanceAboveOrEqualToZero");
      Account account0 = new Account(0L, client0, 0L);
      complianceRuleBalanceAboveOrEqualToZero0.validateAccountCompliance(account0);
      assertEquals(0L, account0.getCurrentBalance());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ComplianceRuleBalanceAboveOrEqualToZero complianceRuleBalanceAboveOrEqualToZero0 = new ComplianceRuleBalanceAboveOrEqualToZero();
      Client client0 = new Client("(_E1xikU X");
      Account account0 = new Account(0L, client0, (-757L));
      complianceRuleBalanceAboveOrEqualToZero0.validateAccountCompliance(account0);
      assertEquals((-757L), account0.getCurrentBalance());
  }
}
