/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:40:48 GMT 2022
 */

package io.diffblue.corebanking.account;

import org.junit.Test;
import static org.junit.Assert.*;
import io.diffblue.corebanking.account.AccountException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AccountException_ESTest extends AccountException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AccountException accountException0 = new AccountException("cIqF+A&r6");
  }
}
