/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:40:38 GMT 2022
 */

package io.diffblue.corebanking.datamanagement;

import org.junit.Test;
import static org.junit.Assert.*;
import io.diffblue.corebanking.CoreBanking;
import io.diffblue.corebanking.datamanagement.WriteToDB;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WriteToDB_ESTest extends WriteToDB_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WriteToDB writeToDB0 = new WriteToDB();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CoreBanking coreBanking0 = new CoreBanking();
      WriteToDB.writeToDisk(coreBanking0);
  }
}
