/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 22 11:39:02 GMT 2022
 */

package io.diffblue.corebanking;

import org.junit.Test;
import static org.junit.Assert.*;
import io.diffblue.corebanking.CoreBankingException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CoreBankingException_ESTest extends CoreBankingException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CoreBankingException coreBankingException0 = new CoreBankingException("");
  }
}
